In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("DATA/allsides.csv")
df.head(25)
left_sources = df[df["bias"]== "left"]
right_sources = df[df["bias"]== "right"]

In [12]:
left_sources.sort_values('agree_ratio', ascending=False).head(10)

,name,bias,total_votes,agree,disagree,agree_ratio,agreeance_text,allsides_page
206,Mother Jones,left,17416,15171,2245,6.757684,Absolutely Agrees,https://www.allsides.com/news-source/mother-jo...
7,AlterNet,left,16591,13639,2952,4.620257,Absolutely Agrees,https://www.allsides.com/news-source/alternet-...
62,CNN (Opinion),left,40486,33168,7318,4.532386,Absolutely Agrees,https://www.allsides.com/news-source/cnn-edito...
89,Democracy Now,left,16298,13250,3048,4.347113,Absolutely Agrees,https://www.allsides.com/news-source/democracy...
371,The New Yorker,left,11568,9323,2245,4.152784,Absolutely Agrees,https://www.allsides.com/news-source/new-yorker
247,PinkNews,left,149,120,29,4.137931,Absolutely Agrees,https://www.allsides.com/news-source/pinknews-...
157,Jacobin,left,1210,974,236,4.127119,Absolutely Agrees,https://www.allsides.com/news-source/jacobin-m...
414,Vice,left,4062,3231,831,3.888087,Absolutely Agrees,https://www.allsides.com/news-source/vice-medi...
207,MSNBC,left,26299,20886,5413,3.858489,Absolutely Agrees,https://www.allsides.com/news-source/msnbc
224,New York Times (Opinion),left,18114,14256,3858,3.695179,Absolutely Agrees,https://www.allsides.com/news-source/new-york-...

Link to most agreed sites that are left leaning :   
['https://www.allsides.com/news-source/mother-jones-bias',  
 'https://www.allsides.com/news-source/alternet-media-bias',    
 'https://www.allsides.com/news-source/cnn-editorial',  
 'https://www.allsides.com/news-source/democracy-now',  
 'https://www.allsides.com/news-source/new-yorker',     
 'https://www.allsides.com/news-source/pinknews-media-bias',    
 'https://www.allsides.com/news-source/jacobin-media-bias',  
 'https://www.allsides.com/news-source/vice-media-bias',      
 'https://www.allsides.com/news-source/msnbc',  
 'https://www.allsides.com/news-source/new-york-times-opinion-media-bias'   ]

In [13]:
right_sources.sort_values('agree_ratio', ascending=False).head(10)

,name,bias,total_votes,agree,disagree,agree_ratio,agreeance_text,allsides_page
149,InfoWars,right,6395,5246,1149,4.565709,Absolutely Agrees,https://www.allsides.com/news-source/infowars
122,Fox News (Opinion),right,34262,27753,6509,4.263789,Absolutely Agrees,https://www.allsides.com/news-source/fox-news-...
370,The National Pulse,right,574,461,113,4.079646,Absolutely Agrees,https://www.allsides.com/news-source/national-...
37,Breitbart News,right,50379,39162,11217,3.491308,Absolutely Agrees,https://www.allsides.com/news-source/breitbart
347,The Federalist,right,11785,9021,2764,3.263748,Absolutely Agrees,https://www.allsides.com/news-source/federalist
400,The Western Journal,right,2322,1747,575,3.038261,Absolutely Agrees,https://www.allsides.com/news-source/western-j...
227,Newsmax - Opinion,right,670,504,166,3.036145,Absolutely Agrees,https://www.allsides.com/news-source/newsmax-o...
322,The American Spectator,right,16056,11908,4148,2.870781,Strongly Agrees,https://www.allsides.com/news-source/american-...
24,Biblical Gender Roles,right,232,172,60,2.866667,Strongly Agrees,https://www.allsides.com/news-source/biblical-...
341,The Daily Wire,right,14290,10511,3779,2.781424,Strongly Agrees,https://www.allsides.com/news-source/daily-wire

['https://www.allsides.com/news-source/infowars',       
 'https://www.allsides.com/news-source/fox-news-editorial-media-bias',      
 'https://www.allsides.com/news-source/national-pulse-media-bias',      
 'https://www.allsides.com/news-source/breitbart',      
 'https://www.allsides.com/news-source/federalist',     
 'https://www.allsides.com/news-source/western-journalism',     
 'https://www.allsides.com/news-source/newsmax-opinion-media-bias',     
 'https://www.allsides.com/news-source/american-spectator',     
 'https://www.allsides.com/news-source/biblical-gender-roles-media-bias',       
 'https://www.allsides.com/news-source/daily-wire']

In [14]:
df.sort_values("total_votes", ascending=False)[:10]

,name,bias,total_votes,agree,disagree,agree_ratio,agreeance_text,allsides_page
401,TheBlaze.com,right,179490,99383,80107,1.240628,Somewhat Agrees,https://www.allsides.com/news-source/theblaze-...
61,CNN (Online News),left,98448,50713,47735,1.062386,Somewhat Agrees,https://www.allsides.com/news-source/cnn-media...
121,Fox News (Online News),right,89187,41644,47543,0.875923,Somewhat Disagrees,https://www.allsides.com/news-source/fox-news-...
223,New York Times (News),left-center,67516,28834,38682,0.745411,Somewhat Disagrees,https://www.allsides.com/news-source/new-york-...
234,NPR (Online News),center,61433,31554,29879,1.056059,Somewhat Agrees,https://www.allsides.com/news-source/npr-media...
427,Washington Post,left-center,59917,35626,24291,1.466634,Somewhat Agrees,https://www.allsides.com/news-source/washingto...
141,HuffPost,left,57607,35386,22221,1.592458,Agrees,https://www.allsides.com/news-source/huffpost-...
21,BBC News,center,54202,29177,25025,1.165914,Somewhat Agrees,https://www.allsides.com/news-source/bbc-news-...
250,Politico,left-center,53411,23285,30126,0.772920,Somewhat Disagrees,https://www.allsides.com/news-source/politico-...
0,ABC News (Online),left-center,53210,35301,17909,1.971132,Agrees,https://www.allsides.com/news-source/abc-news-...

Here are some datasets to consider:

Allsides News Dataset (kaggle and huggingface).     
BASIL https://github.com/launchnlp/BASIL        
MBIC (on kaggle)        
https://huggingface.co/datasets/newsmediabias/news-bias-full-data       
https://www.kaggle.com/datasets/timospinde/babe-media-bias-annotations-by-experts